# Generated by Django 6.0.7 on 2026-08-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author Name')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('publish_year', models.IntegerField(verbose_name='Bublish Year')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='Avilable copies')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
