# Generated by Django 6.0.7 on 2026-08-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
        migrations.AddField(
            model_name='book',
            name='avilable_copies',
            field=models.PositiveIntegerField(default=1, verbose_name='Avilable Copies'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.PositiveIntegerField(default=1, verbose_name='Total Copies'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.IntegerField(verbose_name='Publish Year'),
        ),
    ]
