# Generated by Django 6.0.7 on 2026-08-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_book_copies_book_avilable_copies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='avilable_copies',
            new_name='available_copies',
        ),
    ]
